### ISSUE TITLE
 org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory 

### ISSUE THREAD

**Issue by BigData-YC** [wuchong/flink-sql-submit#1]
Exception in thread "main" org.apache.flink.table.api.ValidationException: SQL validation failed. findAndCreateTableSource failed.
	at org.apache.flink.table.planner.calcite.FlinkPlannerImpl.validate(FlinkPlannerImpl.scala:125)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:82)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convertSqlInsert(SqlToOperationConverter.java:154)
	at org.apache.flink.table.planner.operations.SqlToOperationConverter.convert(SqlToOperationConverter.java:89)
	at org.apache.flink.table.planner.delegation.PlannerBase.parse(PlannerBase.scala:130)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.sqlUpdate(TableEnvironmentImpl.java:335)
	at com.github.wuchong.sqlsubmit.SqlSubmit.callInsertInto(SqlSubmit.java:102)
	at com.github.wuchong.sqlsubmit.SqlSubmit.callCommand(SqlSubmit.java:77)
	at com.github.wuchong.sqlsubmit.SqlSubmit.run(SqlSubmit.java:61)
	at com.github.wuchong.sqlsubmit.SqlSubmit.main(SqlSubmit.java:38)
Caused by: org.apache.flink.table.api.TableException: findAndCreateTableSource failed.
	at org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:67)
Caused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.TableSourceFactory' in
the classpath.

Reason: No context matches.

**Comment by mnloveyx** [comment]
引用 

        
        
		<dependency>
		    <groupId>org.apache.flink</groupId>
		    <artifactId>flink-connector-kafka_2.12</artifactId>
		    <version>1.9.0</version>
		</dependency>
		
		
		<dependency>
		    <groupId>org.apache.flink</groupId>
		    <artifactId>flink-json</artifactId>
		    <version>1.9.0</version>
		</dependency>

		<dependency>
		  <groupId>org.apache.flink</groupId>
		  <artifactId>flink-cep_2.11</artifactId>
		  <version>1.9.0</version>
		</dependency>
		
		<dependency>
				<groupId>mysql</groupId>
				<artifactId>mysql-connector-java</artifactId>
				<version>5.1.34</version>
		</dependency>

**Comment by mnloveyx** [comment]
cep

> 引用
> 
> ```
>     
> 	<dependency>
> 	    <groupId>org.apache.flink</groupId>
> 	    <artifactId>flink-connector-kafka_2.12</artifactId>
> 	    <version>1.9.0</version>
> 	</dependency>
> 	
> 	
> 	<dependency>
> 	    <groupId>org.apache.flink</groupId>
> 	    <artifactId>flink-json</artifactId>
> 	    <version>1.9.0</version>
> 	</dependency>
> 
> 	<dependency>
> 	  <groupId>org.apache.flink</groupId>
> 	  <artifactId>flink-cep_2.11</artifactId>
> 	  <version>1.9.0</version>
> 	</dependency>
> 	
> 	<dependency>
> 			<groupId>mysql</groupId>
> 			<artifactId>mysql-connector-java</artifactId>
> 			<version>5.1.34</version>
> 	</dependency>
> ```

flink-cep_2.11  其中用到了cep 表达式才引用

**Comment by BigData-YC** [comment]
试了一下还是这个错误，好像并没有什么用：
The following factories have been considered:
org.apache.flink.table.catalog.GenericInMemoryCatalogFactory
org.apache.flink.table.planner.delegation.BlinkPlannerFactory
org.apache.flink.table.planner.delegation.BlinkExecutorFactory
org.apache.flink.table.sources.CsvBatchTableSourceFactory
org.apache.flink.table.sources.CsvAppendTableSourceFactory
org.apache.flink.table.sinks.CsvBatchTableSinkFactory
org.apache.flink.table.sinks.CsvAppendTableSinkFactory
org.apache.flink.table.planner.StreamPlannerFactory
org.apache.flink.table.executor.StreamExecutorFactory
org.apache.flink.api.java.io.jdbc.JDBCTableSourceSinkFactory
org.apache.flink.streaming.connectors.kafka.KafkaTableSourceSinkFactory
org.apache.flink.formats.json.JsonRowFormatFactory
	at org.apache.flink.table.factories.TableFactoryService.filterByContext(TableFactoryService.java:283)
	at org.apache.flink.table.factories.TableFactoryService.filter(TableFactoryService.java:191)
	at org.apache.flink.table.factories.TableFactoryService.findSingleInternal(TableFactoryService.java:144)
	at org.apache.flink.table.factories.TableFactoryService.find(TableFactoryService.java:97)
	at org.apache.flink.table.factories.TableFactoryUtil.findAndCreateTableSource(TableFactoryUtil.java:64)
	... 33 more



我是windows系统本地运行出现这个问题，，，在服务器上运行也是这个问题

**Comment by BigData-YC** [comment]
Caused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.TableSourceFactory' in
the classpath.

Reason: No context matches.
会不会是因为jar有重复的

**Comment by BigData-YC** [comment]
Caused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.TableSourceFactory' in
the classpath.

Reason: No context matches.
会不会是因为jar有重复的

**Comment by afan249** [comment]
> Caused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.TableSourceFactory' in
> the classpath.
> 
> Reason: No context matches.
> 会不会是因为jar有重复的

**Comment by afan249** [comment]
create table 语法写的是不是少东西呢

**Comment by turbineyang** [comment]
缺了这俩依赖
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
        </dependency>
        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-json</artifactId>
            <version>${flink.version}</version>
        </dependency>

**Comment by turbineyang** [comment]
缺了这俩依赖
`        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-json</artifactId>
            <version>${flink.version}</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.39</version>
        </dependency>
`

**Comment by BigData-YC** [comment]
多谢楼上各位啦！
其实什么都不缺。。。。。。。。。
只是我改了一个配置： /resources/q1里面的关于kafka版本的配置
本来是'connector.version' = 'universal',
我改成了'connector.version' = '2.11',
其实这个不用改。
再次谢谢各位啦！

**Comment by BigData-YC** [comment]
多谢楼上各位啦！
其实什么都不缺。。。。。。。。。
只是我改了一个配置： /resources/q1里面的关于kafka版本的配置
本来是'connector.version' = 'universal',
我改成了'connector.version' = '2.11',
其实这个不用改。
再次谢谢各位啦！
